[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.93"
arrayvec = "0.7.6"
bitvec = "1.0.1"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
memchr = "2.7.4"
seq-macro = "0.3.5"
smallvec = "1.13.2"
